# Generated by Django 2.2 on 2019-11-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='draft_status',
            field=models.NullBooleanField(default=None),
        ),
    ]
